# Generated by Django 4.1.2 on 2023-10-30 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_delete_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watched_listings',
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('watched_listings', models.ManyToManyField(blank=True, related_name='listings', to='auctions.listing')),
            ],
        ),
    ]
